### ISSUE TITLE
Exchange SDP failure

### ISSUE THREAD

**Issue by kane9527-e** [adcimon/unity-srs-template#1]
Exchange SDP failure, url=http://localhost:1985/rtc/v1/whip/?app=live&stream=livestream error=System.AggregateException: One or more errors occurred. (An error occurred while sending the request) ---> System.Net.Http.HttpRequestException: An error occurred while sending the request ---> System.Net.WebException: Error getting response stream (ReadDoneAsync2): ReceiveFailure
![Uploading image.png…]()

**Comment by adcimon** [comment]
This project needs a reachable SRS server deployed as the README.md indicates. I would suggest you to start by reading the official SRS deployment instructions: https://ossrs.io/lts/en-us/docs/v5/doc/getting-started
